export const CIRCUIT_PROFILES = {
  'Spa-Francorchamps': {
    power:      90,
    qualifying: 65,
    overtaking: 75,
    tyreDeg:    60,
    wetSensitivity: 95,
    characteristics: ['High speed', 'Power circuit', 'Wet specialist advantage'],
  },
  'Silverstone': {
    power:      75,
    qualifying: 70,
    overtaking: 70,
    tyreDeg:    75,
    wetSensitivity: 70,
    characteristics: ['Technical', 'Balanced', 'Tyre management key'],
  },
  'Budapest': {
    power:      40,
    qualifying: 95,
    overtaking: 20,
    tyreDeg:    80,
    wetSensitivity: 60,
    characteristics: ['Monaco of modern circuits', 'Qualifying dominant', 'No overtaking'],
  },
  'Zandvoort': {
    power:      55,
    qualifying: 85,
    overtaking: 25,
    tyreDeg:    85,
    wetSensitivity: 65,
    characteristics: ['Banking corners', 'Qualifying dominant', 'High tyre deg'],
  },
  'Monza': {
    power:      100,
    qualifying: 80,
    overtaking: 85,
    tyreDeg:    40,
    wetSensitivity: 55,
    characteristics: ['Temple of speed', 'Pure power', 'Slipstream battles'],
  },
  'Spielberg': {
    power:      80,
    qualifying: 70,
    overtaking: 70,
    tyreDeg:    65,
    wetSensitivity: 60,
    characteristics: ['Short lap', 'Power sensitive', 'Active Aero zones'],
  },
  'Baku': {
    power:      85,
    qualifying: 70,
    overtaking: 80,
    tyreDeg:    50,
    wetSensitivity: 75,
    characteristics: ['Street circuit', 'Safety car magnet', 'Chaos factor'],
  },
  'Marina Bay': {
    power:      50,
    qualifying: 90,
    overtaking: 30,
    tyreDeg:    70,
    wetSensitivity: 80,
    characteristics: ['Night race', 'Street circuit', 'Safety car common'],
  },
  'Austin': {
    power:      65,
    qualifying: 70,
    overtaking: 75,
    tyreDeg:    75,
    wetSensitivity: 65,
    characteristics: ['Flowing layout', 'Balanced circuit', 'US Grand Prix'],
  },
  'Mexico City': {
    power:      90,
    qualifying: 80,
    overtaking: 55,
    tyreDeg:    50,
    wetSensitivity: 40,
    characteristics: ['High altitude', 'Engine performance', 'Low drag setup'],
  },
  'Sao Paulo': {
    power:      70,
    qualifying: 65,
    overtaking: 80,
    tyreDeg:    70,
    wetSensitivity: 85,
    characteristics: ['Anti-clockwise', 'Elevation changes', 'Rain risk'],
  },
  'Monte Carlo': {
    power:      40,
    qualifying: 100,
    overtaking: 5,
    tyreDeg:    45,
    wetSensitivity: 90,
    characteristics: ['Qualifying everything', 'No overtaking', 'Prestige race'],
  },
  'Barcelona': {
    power:      65,
    qualifying: 75,
    overtaking: 55,
    tyreDeg:    85,
    wetSensitivity: 60,
    characteristics: ['Technical circuit', 'Tyre management', 'Development track'],
  },
};

export function getCircuitProfile(location) {
  return CIRCUIT_PROFILES[location] || {
    power: 70, qualifying: 70, overtaking: 60,
    tyreDeg: 65, wetSensitivity: 60,
    characteristics: ['Data unavailable'],
  };
}